#!/usr/bin/env bash
set -euo pipefail

# idempotent installer for HeartMula on ADA2 (Ubuntu/Debian-like)
# - creates heartmula user
# - creates venv at /var/lib/heartmula/env
# - installs system packages, python packages, tries to install Triton
# - clones heartlib and installs it
# - creates /etc/heartmula/heartmula.env and systemd service
# - enables and starts service and performs a health check

HEARTMULA_USER=${HEARTMULA_USER:-heartmula}
HEARTMULA_HOME=${HEARTMULA_HOME:-/var/lib/heartmula}
VENV_PATH="$HEARTMULA_HOME/env"
ENV_FILE="/etc/heartmula/heartmula.env"
SERVICE_FILE="/etc/systemd/system/heartmula.service"
REPO_URL="https://github.com/HeartMuLa/heartlib.git"
PYTHON_BIN=${PYTHON_BIN:-python3.10}

function ensure_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "This installer must be run as root (sudo)."
    exit 1
  fi
}

function create_user() {
  if id -u "$HEARTMULA_USER" >/dev/null 2>&1; then
    echo "User $HEARTMULA_USER already exists"
  else
    echo "Creating system user $HEARTMULA_USER..."
    useradd --system --create-home --home-dir "$HEARTMULA_HOME" --shell /bin/bash "$HEARTMULA_USER"
    mkdir -p "$HEARTMULA_HOME"
    chown -R "$HEARTMULA_USER":"$HEARTMULA_USER" "$HEARTMULA_HOME"
  fi
}

function apt_install_prereqs() {
  echo "Installing apt packages (build tools, python3.10, libs)..."
  apt-get update
  apt-get install -y --no-install-recommends \
    build-essential git ca-certificates curl wget python3.10 python3.10-venv python3.10-dev \
    libsndfile1 libopenblas-dev pkg-config
}

function check_cuda() {
  if command -v nvidia-smi >/dev/null 2>&1; then
    echo "NVIDIA GPU detected (nvidia-smi found)"
    nvidia-smi
    return 0
  fi
  echo "Warning: nvidia-smi not found. CUDA may not be installed or drivers are missing." >&2
  return 1
}

function create_venv_and_install_python_pkgs() {
  if [ ! -d "$VENV_PATH" ]; then
    echo "Creating venv at $VENV_PATH"
    sudo -u "$HEARTMULA_USER" -H "$PYTHON_BIN" -m venv "$VENV_PATH"
  else
    echo "Venv already exists at $VENV_PATH"
  fi

  PIP="$VENV_PATH/bin/pip"
  PY="$VENV_PATH/bin/python"

  "$PIP" install --upgrade pip setuptools wheel

  # Attempt to install a CUDA-enabled PyTorch if a GPU is present.
  if check_cuda; then
    echo "Attempting to install GPU-enabled PyTorch (cu118)"
    if "$PIP" install --index-url https://download.pytorch.org/whl/cu118 torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118; then
      echo "Installed PyTorch (cu118)"
    else
      echo "Failed to install cu118 wheels; attempting cpu torch wheel as fallback"
      "$PIP" install torch torchvision --index-url https://download.pytorch.org/whl/cpu
    fi
  else
    echo "Installing CPU PyTorch wheel"
    "$PIP" install torch torchvision --index-url https://download.pytorch.org/whl/cpu
  fi

  # Install runtime deps
  "$PIP" install fastapi uvicorn soundfile pydantic

  # Clone and install heartlib (editable)
  if [ ! -d "$HEARTMULA_HOME/heartlib" ]; then
    sudo -u "$HEARTMULA_USER" -H git clone "$REPO_URL" "$HEARTMULA_HOME/heartlib"
  else
    echo "heartlib already cloned"
    pushd "$HEARTMULA_HOME/heartlib" >/dev/null
    sudo -u "$HEARTMULA_USER" -H git pull --ff-only || true
    popd >/dev/null
  fi

  pushd "$HEARTMULA_HOME/heartlib" >/dev/null
  "$PIP" install -e . || true
  popd >/dev/null

  # Deploy the HeartMula FastAPI shim into the runtime dir if available (idempotent)
  SHIM_SRC="$(cd "$(dirname "$0")/.." && pwd)/heartmula_server.py"
  if [ -f "$SHIM_SRC" ]; then
    echo "Copying HeartMula shim from $SHIM_SRC to $HEARTMULA_HOME/heartmula_server.py"
    cp -f "$SHIM_SRC" "$HEARTMULA_HOME/heartmula_server.py"
    chown "$HEARTMULA_USER":"$HEARTMULA_USER" "$HEARTMULA_HOME/heartmula_server.py"
    chmod 644 "$HEARTMULA_HOME/heartmula_server.py"
  else
    echo "Note: heartmula_server.py not found next to scripts (expected at $SHIM_SRC). If you cloned ai-infra elsewhere, copy the shim to $HEARTMULA_HOME/heartmula_server.py"
  fi

  # Try installing Triton (best-effort; may fail on some systems)
  echo "Attempting to install triton (optional acceleration). This may fail — if so, skip it and continue."
  if "$PIP" install triton; then
    echo "Triton installed"
  else
    echo "Triton installation failed; you can try manual installation on ada2 if desired." >&2
  fi
}

function write_env_file() {
  mkdir -p "$(dirname "$ENV_FILE")"
  cat >"$ENV_FILE" <<EOF
# HeartMula environment (generated by install_ada2.sh)
HEARTMULA_MODEL_PATH=/var/lib/heartmula/ckpt
HEARTMULA_OUTPUT_DIR=/var/lib/heartmula/output
# Default to 0.0.0.0 so the gateway (on a separate host) can reach this service.
# WARNING: binding to 0.0.0.0 exposes the service to the network —
# ensure firewall rules / security groups restrict access to trusted hosts (e.g., the gateway).
HEARTMULA_HOST=0.0.0.0
HEARTMULA_PORT=9920
HEARTMULA_DEVICE=cuda
HEARTMULA_DTYPE=float16
HEARTMULA_VERSION=1B
# Optional: allowed CIDR(s) to permit to connect to HeartMula port (space-separated list)
HEARTMULA_ALLOWED_CIDRS="10.10.22.0/24"
# PyTorch CUDA memory management to avoid fragmentation
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:512
EOF
  chmod 644 "$ENV_FILE"
  chown root:root "$ENV_FILE"
}

function install_systemd_service() {
  echo "Installing systemd unit file to $SERVICE_FILE"
  mkdir -p "$(dirname "$SERVICE_FILE")"
  cat >"$SERVICE_FILE" <<EOF
[Unit]
Description=HeartMula Music Generation Service
After=network.target

[Service]
Type=simple
User=$HEARTMULA_USER
Group=$HEARTMULA_USER
EnvironmentFile=$ENV_FILE
WorkingDirectory=$HEARTMULA_HOME
ExecStart=$VENV_PATH/bin/python $HEARTMULA_HOME/heartmula_server.py
Restart=on-failure
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now heartmula.service || true
}

function configure_firewall() {
  # Configure iptables to allow only the subnets in HEARTMULA_ALLOWED_CIDRS to access HEARTMULA_PORT
  if ! command -v iptables >/dev/null 2>&1; then
    echo "iptables not found; skipping firewall configuration"
    return
  fi

  port=$(awk -F= '/HEARTMULA_PORT/{print $2}' "$ENV_FILE" | tr -d ' ')
  port=${port:-9920}
  allowed=$(awk -F= '/HEARTMULA_ALLOWED_CIDRS/{print $2}' "$ENV_FILE" | tr -d '"')
  allowed=${allowed:-10.10.22.0/24}

  echo "Configuring iptables: allowing $allowed to access port $port and dropping other sources"

  # Install persistence helper
  DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent || true

  for cidr in $allowed; do
    if ! iptables -C INPUT -p tcp -s "$cidr" --dport "$port" -j ACCEPT >/dev/null 2>&1; then
      iptables -I INPUT -p tcp -s "$cidr" --dport "$port" -j ACCEPT
    fi
  done

  if ! iptables -C INPUT -p tcp --dport "$port" -j DROP >/dev/null 2>&1; then
    iptables -A INPUT -p tcp --dport "$port" -j DROP
  fi

  # Save rules
  netfilter-persistent save || iptables-save > /etc/iptables/rules.v4 || true
}


function smoke_check() {
  local tries=12
  local port=$(awk -F= '/HEARTMULA_PORT/{print $2}' "$ENV_FILE" | tr -d ' ')
  port=${port:-9920}
  echo "Waiting for HeartMula health on 127.0.0.1:$port"
  for i in $(seq 1 $tries); do
    if curl -fsS "http://127.0.0.1:$port/health" >/dev/null 2>&1; then
      echo "HeartMula is healthy"
      return 0
    fi
    sleep 5
  done
  echo "HeartMula failed to respond to health check" >&2
  journalctl -u heartmula.service --no-pager -n 200 || true
  return 1
}

function main() {
  ensure_root
  apt_install_prereqs
  create_user
  create_venv_and_install_python_pkgs
  write_env_file
  install_systemd_service
  configure_firewall
  smoke_check || true
  echo "Install complete. If the service failed to start, check logs: sudo journalctl -u heartmula.service -n 200"
}

main "$@"
